"""make_weight_optional_in_medical_records

Revision ID: 06bdb1979ddf
Revises: 5b96dc187193
Create Date: 2025-11-16 15:31:56.599156

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "06bdb1979ddf"
down_revision: str | None = "5b96dc187193"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLiteではALTER COLUMNがサポートされていないため、テーブルを再作成する必要がある
    # しかし、既存データがあるため、バッチ操作を使用
    with op.batch_alter_table("medical_records", schema=None) as batch_op:
        batch_op.alter_column(
            "weight", existing_type=sa.NUMERIC(precision=5, scale=2), nullable=True
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("medical_records", schema=None) as batch_op:
        batch_op.alter_column(
            "weight", existing_type=sa.NUMERIC(precision=5, scale=2), nullable=False
        )
    # ### end Alembic commands ###
