"""Add unit column to medical_actions

Revision ID: 5b96dc187193
Revises: 10749c886a42
Create Date: 2025-11-15 23:35:05.141941

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5b96dc187193"
down_revision: str | None = "10749c886a42"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add unit column to medical_actions table
    op.add_column(
        "medical_actions",
        sa.Column(
            "unit",
            sa.String(length=20),
            nullable=True,
            comment="投薬単位（ml、錠、回等）",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove unit column from medical_actions table
    op.drop_column("medical_actions", "unit")
    # ### end Alembic commands ###


def downgrade_old() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "applicants",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), nullable=False),
        sa.Column("contact", sa.VARCHAR(length=255), nullable=False),
        sa.Column("address", sa.TEXT(), nullable=True),
        sa.Column("family", sa.TEXT(), nullable=True),
        sa.Column("environment", sa.TEXT(), nullable=True),
        sa.Column("conditions", sa.TEXT(), nullable=True),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_applicants_name", "applicants", ["name"], unique=False)
    op.create_index("ix_applicants_contact", "applicants", ["contact"], unique=False)
    op.create_table(
        "volunteers",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), nullable=False),
        sa.Column("contact", sa.VARCHAR(length=255), nullable=True),
        sa.Column("affiliation", sa.VARCHAR(length=100), nullable=True),
        sa.Column(
            "status",
            sa.VARCHAR(length=20),
            server_default=sa.text("'active'"),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DATE(),
            server_default=sa.text("(CURRENT_DATE)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_volunteers_status", "volunteers", ["status"], unique=False)
    op.create_index("ix_volunteers_name", "volunteers", ["name"], unique=False)
    op.create_table(
        "animal_images",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("animal_id", sa.INTEGER(), nullable=False),
        sa.Column("image_path", sa.VARCHAR(length=255), nullable=False),
        sa.Column("taken_at", sa.DATE(), nullable=True),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column(
            "file_size", sa.INTEGER(), server_default=sa.text("'0'"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["animal_id"], ["animals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_animal_images_taken_at", "animal_images", ["taken_at"], unique=False
    )
    op.create_index(
        "ix_animal_images_animal_id", "animal_images", ["animal_id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("email", sa.VARCHAR(length=255), nullable=False),
        sa.Column("password_hash", sa.VARCHAR(length=255), nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), nullable=False),
        sa.Column(
            "role",
            sa.VARCHAR(length=20),
            server_default=sa.text("'read_only'"),
            nullable=False,
        ),
        sa.Column(
            "is_active", sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False
        ),
        sa.Column(
            "failed_login_count",
            sa.INTEGER(),
            server_default=sa.text("'0'"),
            nullable=False,
        ),
        sa.Column("locked_until", sa.DATETIME(), nullable=True),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index("ix_users_role", "users", ["role"], unique=False)
    op.create_index("ix_users_email", "users", ["email"], unique=False)
    op.create_table(
        "status_history",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("animal_id", sa.INTEGER(), nullable=False),
        sa.Column("old_status", sa.VARCHAR(length=20), nullable=True),
        sa.Column("new_status", sa.VARCHAR(length=20), nullable=False),
        sa.Column("reason", sa.TEXT(), nullable=True),
        sa.Column("changed_by", sa.INTEGER(), nullable=True),
        sa.Column(
            "changed_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["animal_id"], ["animals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["changed_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_status_history_changed_at", "status_history", ["changed_at"], unique=False
    )
    op.create_index(
        "ix_status_history_animal_id", "status_history", ["animal_id"], unique=False
    )
    op.create_table(
        "medical_records",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("animal_id", sa.INTEGER(), nullable=False),
        sa.Column("vet_id", sa.INTEGER(), nullable=False),
        sa.Column("date", sa.DATE(), nullable=False),
        sa.Column("time_slot", sa.VARCHAR(length=20), nullable=True),
        sa.Column("weight", sa.NUMERIC(precision=5, scale=2), nullable=False),
        sa.Column("temperature", sa.NUMERIC(precision=4, scale=1), nullable=True),
        sa.Column("symptoms", sa.TEXT(), nullable=False),
        sa.Column("medical_action_id", sa.INTEGER(), nullable=True),
        sa.Column("dosage", sa.INTEGER(), nullable=True),
        sa.Column("other", sa.TEXT(), nullable=True),
        sa.Column("comment", sa.TEXT(), nullable=True),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "last_updated_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("last_updated_by", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(["animal_id"], ["animals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["last_updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["medical_action_id"], ["medical_actions.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["vet_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_medical_records_vet_id", "medical_records", ["vet_id"], unique=False
    )
    op.create_index(
        "ix_medical_records_medical_action_id",
        "medical_records",
        ["medical_action_id"],
        unique=False,
    )
    op.create_index(
        "ix_medical_records_date", "medical_records", ["date"], unique=False
    )
    op.create_index(
        "ix_medical_records_animal_id", "medical_records", ["animal_id"], unique=False
    )
    op.create_table(
        "medical_actions",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), nullable=False),
        sa.Column("valid_from", sa.DATE(), nullable=False),
        sa.Column("valid_to", sa.DATE(), nullable=True),
        sa.Column(
            "cost_price",
            sa.NUMERIC(precision=10, scale=2),
            server_default=sa.text("'0.00'"),
            nullable=False,
        ),
        sa.Column(
            "selling_price",
            sa.NUMERIC(precision=10, scale=2),
            server_default=sa.text("'0.00'"),
            nullable=False,
        ),
        sa.Column(
            "procedure_fee",
            sa.NUMERIC(precision=10, scale=2),
            server_default=sa.text("'0.00'"),
            nullable=False,
        ),
        sa.Column(
            "currency",
            sa.VARCHAR(length=3),
            server_default=sa.text("'JPY'"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "last_updated_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("last_updated_by", sa.INTEGER(), nullable=True),
        sa.ForeignKeyConstraint(["last_updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_medical_actions_valid_to", "medical_actions", ["valid_to"], unique=False
    )
    op.create_index(
        "ix_medical_actions_valid_from", "medical_actions", ["valid_from"], unique=False
    )
    op.create_index(
        "ix_medical_actions_name", "medical_actions", ["name"], unique=False
    )
    op.create_table(
        "adoption_records",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("animal_id", sa.INTEGER(), nullable=False),
        sa.Column("applicant_id", sa.INTEGER(), nullable=False),
        sa.Column("interview_date", sa.DATE(), nullable=True),
        sa.Column("interview_note", sa.TEXT(), nullable=True),
        sa.Column("decision", sa.VARCHAR(length=20), nullable=True),
        sa.Column("adoption_date", sa.DATE(), nullable=True),
        sa.Column("follow_up", sa.TEXT(), nullable=True),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["animal_id"], ["animals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["applicant_id"], ["applicants.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_adoption_records_applicant_id",
        "adoption_records",
        ["applicant_id"],
        unique=False,
    )
    op.create_index(
        "ix_adoption_records_animal_id", "adoption_records", ["animal_id"], unique=False
    )
    op.create_index(
        "ix_adoption_records_adoption_date",
        "adoption_records",
        ["adoption_date"],
        unique=False,
    )
    op.create_table(
        "settings",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("key", sa.VARCHAR(length=100), nullable=False),
        sa.Column("value", sa.TEXT(), nullable=True),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_index("ix_settings_key", "settings", ["key"], unique=False)
    op.create_table(
        "animals",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=100), nullable=True),
        sa.Column("photo", sa.VARCHAR(length=255), nullable=False),
        sa.Column("pattern", sa.VARCHAR(length=100), nullable=False),
        sa.Column("tail_length", sa.VARCHAR(length=50), nullable=False),
        sa.Column("collar", sa.VARCHAR(length=100), nullable=True),
        sa.Column("age", sa.VARCHAR(length=50), nullable=False),
        sa.Column("gender", sa.VARCHAR(length=10), nullable=False),
        sa.Column(
            "ear_cut", sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False
        ),
        sa.Column("features", sa.TEXT(), nullable=True),
        sa.Column(
            "status",
            sa.VARCHAR(length=20),
            server_default=sa.text("'保護中'"),
            nullable=False,
        ),
        sa.Column(
            "protected_at",
            sa.DATE(),
            server_default=sa.text("(CURRENT_DATE)"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_animals_status", "animals", ["status"], unique=False)
    op.create_index(
        "ix_animals_protected_at", "animals", ["protected_at"], unique=False
    )
    op.create_index("ix_animals_name", "animals", ["name"], unique=False)
    op.create_table(
        "care_logs",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("animal_id", sa.INTEGER(), nullable=False),
        sa.Column("recorder_id", sa.INTEGER(), nullable=True),
        sa.Column("recorder_name", sa.VARCHAR(length=100), nullable=False),
        sa.Column("time_slot", sa.VARCHAR(length=10), nullable=False),
        sa.Column(
            "appetite", sa.INTEGER(), server_default=sa.text("'3'"), nullable=False
        ),
        sa.Column(
            "energy", sa.INTEGER(), server_default=sa.text("'3'"), nullable=False
        ),
        sa.Column(
            "urination", sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False
        ),
        sa.Column(
            "cleaning", sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False
        ),
        sa.Column("memo", sa.TEXT(), nullable=True),
        sa.Column("ip_address", sa.VARCHAR(length=45), nullable=True),
        sa.Column("user_agent", sa.VARCHAR(length=255), nullable=True),
        sa.Column("device_tag", sa.VARCHAR(length=100), nullable=True),
        sa.Column(
            "from_paper", sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "last_updated_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("last_updated_by", sa.INTEGER(), nullable=True),
        sa.Column(
            "log_date",
            sa.DATE(),
            server_default=sa.text("(CURRENT_DATE)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["animal_id"], ["animals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["last_updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["recorder_id"], ["volunteers.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_care_logs_time_slot", "care_logs", ["time_slot"], unique=False)
    op.create_index(
        "ix_care_logs_recorder_id", "care_logs", ["recorder_id"], unique=False
    )
    op.create_index("ix_care_logs_log_date", "care_logs", ["log_date"], unique=False)
    op.create_index(
        "ix_care_logs_created_at", "care_logs", ["created_at"], unique=False
    )
    op.create_index("ix_care_logs_animal_id", "care_logs", ["animal_id"], unique=False)
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=True),
        sa.Column("action", sa.VARCHAR(length=50), nullable=False),
        sa.Column("target_type", sa.VARCHAR(length=50), nullable=False),
        sa.Column("target_id", sa.INTEGER(), nullable=True),
        sa.Column("details", sa.TEXT(), nullable=True),
        sa.Column("ip_address", sa.VARCHAR(length=45), nullable=True),
        sa.Column("user_agent", sa.VARCHAR(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DATETIME(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_logs_user_id", "audit_logs", ["user_id"], unique=False)
    op.create_index(
        "ix_audit_logs_target_type", "audit_logs", ["target_type"], unique=False
    )
    op.create_index(
        "ix_audit_logs_created_at", "audit_logs", ["created_at"], unique=False
    )
    op.create_index("ix_audit_logs_action", "audit_logs", ["action"], unique=False)
    # ### end Alembic commands ###
