"""Add rescue_source and breed to animals

Revision ID: 72a47062ea9d
Revises: b91_extend_applicant
Create Date: 2026-01-18 01:57:33.016190

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "72a47062ea9d"
down_revision: str | None = "b91_extend_applicant"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "animals",
        sa.Column(
            "rescue_source",
            sa.String(length=200),
            nullable=True,
            comment="レスキュー元",
        ),
    )
    op.add_column(
        "animals",
        sa.Column("breed", sa.String(length=100), nullable=True, comment="品種"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("animals", "breed")
    op.drop_column("animals", "rescue_source")
    # ### end Alembic commands ###
