"""Initial migration

Revision ID: ca739447407b
Revises:
Create Date: 2025-11-12 20:05:57.172005

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ca739447407b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "animals",
        sa.Column(
            "id", sa.Integer(), autoincrement=True, nullable=False, comment="主キー"
        ),
        sa.Column("name", sa.String(length=100), nullable=True, comment="猫の名前"),
        sa.Column(
            "photo",
            sa.String(length=255),
            nullable=False,
            comment="顔写真のファイルパス",
        ),
        sa.Column(
            "pattern",
            sa.String(length=100),
            nullable=False,
            comment="柄・色（例: キジトラ、三毛、黒猫）",
        ),
        sa.Column(
            "tail_length",
            sa.String(length=50),
            nullable=False,
            comment="尻尾の長さ（例: 長い、短い、なし）",
        ),
        sa.Column(
            "collar",
            sa.String(length=100),
            nullable=True,
            comment="首輪の有無と色（例: 赤い首輪、首輪なし）",
        ),
        sa.Column(
            "age",
            sa.String(length=50),
            nullable=False,
            comment="年齢・大きさ（例: 子猫、成猫、老猫）",
        ),
        sa.Column(
            "gender",
            sa.String(length=10),
            nullable=False,
            comment="性別（male/female/unknown）",
        ),
        sa.Column(
            "ear_cut",
            sa.Boolean(),
            server_default="0",
            nullable=False,
            comment="耳カットの有無（TNR済みの印）",
        ),
        sa.Column(
            "features", sa.Text(), nullable=True, comment="外傷・特徴・性格（自由記述）"
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default="保護中",
            nullable=False,
            comment="ステータス（保護中、譲渡可能、譲渡済み、治療中など）",
        ),
        sa.Column(
            "protected_at",
            sa.Date(),
            server_default=sa.text("(CURRENT_DATE)"),
            nullable=False,
            comment="保護日",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="作成日時",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="更新日時",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_animals_name", "animals", ["name"], unique=False)
    op.create_index(
        "ix_animals_protected_at", "animals", ["protected_at"], unique=False
    )
    op.create_index("ix_animals_status", "animals", ["status"], unique=False)
    op.create_table(
        "applicants",
        sa.Column(
            "id", sa.Integer(), autoincrement=True, nullable=False, comment="主キー"
        ),
        sa.Column("name", sa.String(length=100), nullable=False, comment="氏名"),
        sa.Column(
            "contact",
            sa.String(length=255),
            nullable=False,
            comment="連絡先（電話番号、メールアドレス等）",
        ),
        sa.Column("address", sa.Text(), nullable=True, comment="住所"),
        sa.Column("family", sa.Text(), nullable=True, comment="家族構成"),
        sa.Column("environment", sa.Text(), nullable=True, comment="飼育環境"),
        sa.Column("conditions", sa.Text(), nullable=True, comment="希望条件"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="作成日時",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="更新日時",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_applicants_contact", "applicants", ["contact"], unique=False)
    op.create_index("ix_applicants_name", "applicants", ["name"], unique=False)
    op.create_table(
        "settings",
        sa.Column(
            "id", sa.Integer(), autoincrement=True, nullable=False, comment="主キー"
        ),
        sa.Column(
            "key", sa.String(length=100), nullable=False, comment="設定キー（ユニーク）"
        ),
        sa.Column("value", sa.Text(), nullable=True, comment="設定値"),
        sa.Column("description", sa.Text(), nullable=True, comment="説明"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="作成日時",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="更新日時",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key"),
    )
    op.create_index("ix_settings_key", "settings", ["key"], unique=True)
    op.create_table(
        "users",
        sa.Column(
            "id", sa.Integer(), autoincrement=True, nullable=False, comment="主キー"
        ),
        sa.Column(
            "email",
            sa.String(length=255),
            nullable=False,
            comment="メールアドレス（ログインID）",
        ),
        sa.Column(
            "password_hash",
            sa.String(length=255),
            nullable=False,
            comment="パスワードハッシュ（bcrypt）",
        ),
        sa.Column("name", sa.String(length=100), nullable=False, comment="氏名"),
        sa.Column(
            "role",
            sa.String(length=20),
            server_default="read_only",
            nullable=False,
            comment="ロール（admin/staff/vet/read_only）",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default="1",
            nullable=False,
            comment="アクティブ状態（True=有効、False=無効）",
        ),
        sa.Column(
            "failed_login_count",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="ログイン失敗回数",
        ),
        sa.Column(
            "locked_until",
            sa.DateTime(),
            nullable=True,
            comment="ロック解除日時（5回失敗後15分間ロック）",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="作成日時",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="更新日時",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index("ix_users_email", "users", ["email"], unique=True)
    op.create_index("ix_users_role", "users", ["role"], unique=False)
    op.create_table(
        "volunteers",
        sa.Column(
            "id", sa.Integer(), autoincrement=True, nullable=False, comment="主キー"
        ),
        sa.Column("name", sa.String(length=100), nullable=False, comment="氏名"),
        sa.Column(
            "contact",
            sa.String(length=255),
            nullable=True,
            comment="連絡先（電話番号、メールアドレス等）",
        ),
        sa.Column(
            "affiliation",
            sa.String(length=100),
            nullable=True,
            comment="所属（団体名等）",
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            server_default="active",
            nullable=False,
            comment="活動状態（active/inactive）",
        ),
        sa.Column(
            "started_at",
            sa.Date(),
            server_default=sa.text("(CURRENT_DATE)"),
            nullable=False,
            comment="活動開始日",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="作成日時",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="更新日時",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_volunteers_name", "volunteers", ["name"], unique=False)
    op.create_index("ix_volunteers_status", "volunteers", ["status"], unique=False)
    op.create_table(
        "adoption_records",
        sa.Column(
            "id", sa.Integer(), autoincrement=True, nullable=False, comment="主キー"
        ),
        sa.Column("animal_id", sa.Integer(), nullable=False, comment="猫ID"),
        sa.Column("applicant_id", sa.Integer(), nullable=False, comment="里親希望者ID"),
        sa.Column("interview_date", sa.Date(), nullable=True, comment="面談日"),
        sa.Column("interview_note", sa.Text(), nullable=True, comment="面談内容"),
        sa.Column(
            "decision",
            sa.String(length=20),
            nullable=True,
            comment="判定結果（approved/rejected/pending）",
        ),
        sa.Column("adoption_date", sa.Date(), nullable=True, comment="譲渡日"),
        sa.Column("follow_up", sa.Text(), nullable=True, comment="譲渡後フォロー"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="作成日時",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="更新日時",
        ),
        sa.ForeignKeyConstraint(["animal_id"], ["animals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["applicant_id"], ["applicants.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_adoption_records_adoption_date",
        "adoption_records",
        ["adoption_date"],
        unique=False,
    )
    op.create_index(
        "ix_adoption_records_animal_id", "adoption_records", ["animal_id"], unique=False
    )
    op.create_index(
        "ix_adoption_records_applicant_id",
        "adoption_records",
        ["applicant_id"],
        unique=False,
    )
    op.create_table(
        "animal_images",
        sa.Column(
            "id", sa.Integer(), autoincrement=True, nullable=False, comment="主キー"
        ),
        sa.Column("animal_id", sa.Integer(), nullable=False, comment="猫ID"),
        sa.Column(
            "image_path",
            sa.String(length=255),
            nullable=False,
            comment="画像ファイルパス",
        ),
        sa.Column("taken_at", sa.Date(), nullable=True, comment="撮影日"),
        sa.Column("description", sa.Text(), nullable=True, comment="説明"),
        sa.Column(
            "file_size",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="ファイルサイズ（bytes）",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="作成日時",
        ),
        sa.ForeignKeyConstraint(["animal_id"], ["animals.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_animal_images_animal_id", "animal_images", ["animal_id"], unique=False
    )
    op.create_index(
        "ix_animal_images_taken_at", "animal_images", ["taken_at"], unique=False
    )
    op.create_table(
        "audit_logs",
        sa.Column(
            "id", sa.Integer(), autoincrement=True, nullable=False, comment="主キー"
        ),
        sa.Column("user_id", sa.Integer(), nullable=True, comment="操作者ID"),
        sa.Column(
            "action",
            sa.String(length=50),
            nullable=False,
            comment="操作種別（create_animal, update_status等）",
        ),
        sa.Column(
            "target_type",
            sa.String(length=50),
            nullable=False,
            comment="対象テーブル（animals, users等）",
        ),
        sa.Column("target_id", sa.Integer(), nullable=True, comment="対象レコードID"),
        sa.Column("details", sa.Text(), nullable=True, comment="詳細情報（JSON形式）"),
        sa.Column(
            "ip_address",
            sa.String(length=45),
            nullable=True,
            comment="IPアドレス（IPv6対応）",
        ),
        sa.Column(
            "user_agent",
            sa.String(length=255),
            nullable=True,
            comment="ユーザーエージェント",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="操作日時",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_logs_action", "audit_logs", ["action"], unique=False)
    op.create_index(
        "ix_audit_logs_created_at", "audit_logs", ["created_at"], unique=False
    )
    op.create_index(
        "ix_audit_logs_target_type", "audit_logs", ["target_type"], unique=False
    )
    op.create_index("ix_audit_logs_user_id", "audit_logs", ["user_id"], unique=False)
    op.create_table(
        "care_logs",
        sa.Column(
            "id", sa.Integer(), autoincrement=True, nullable=False, comment="主キー"
        ),
        sa.Column("animal_id", sa.Integer(), nullable=False, comment="猫ID"),
        sa.Column(
            "recorder_id",
            sa.Integer(),
            nullable=True,
            comment="記録者ID（ボランティアテーブル）",
        ),
        sa.Column(
            "recorder_name", sa.String(length=100), nullable=False, comment="記録者名"
        ),
        sa.Column(
            "time_slot",
            sa.String(length=10),
            nullable=False,
            comment="時点（morning/noon/evening）",
        ),
        sa.Column(
            "appetite",
            sa.Integer(),
            server_default="3",
            nullable=False,
            comment="食欲（1〜5段階、5が最良）",
        ),
        sa.Column(
            "energy",
            sa.Integer(),
            server_default="3",
            nullable=False,
            comment="元気（1〜5段階、5が最良）",
        ),
        sa.Column(
            "urination",
            sa.Boolean(),
            server_default="0",
            nullable=False,
            comment="排尿有無（True=有り、False=無し）",
        ),
        sa.Column(
            "cleaning",
            sa.Boolean(),
            server_default="0",
            nullable=False,
            comment="清掃済み（True=済、False=未）",
        ),
        sa.Column("memo", sa.Text(), nullable=True, comment="メモ"),
        sa.Column(
            "ip_address",
            sa.String(length=45),
            nullable=True,
            comment="IPアドレス（IPv6対応）",
        ),
        sa.Column(
            "user_agent",
            sa.String(length=255),
            nullable=True,
            comment="ユーザーエージェント",
        ),
        sa.Column(
            "device_tag",
            sa.String(length=100),
            nullable=True,
            comment="デバイスタグ（端末識別用）",
        ),
        sa.Column(
            "from_paper",
            sa.Boolean(),
            server_default="0",
            nullable=False,
            comment="紙記録からの転記フラグ",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="記録日時",
        ),
        sa.Column(
            "last_updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="最終更新日時",
        ),
        sa.Column(
            "last_updated_by",
            sa.Integer(),
            nullable=True,
            comment="最終更新者ID（管理者による修正時）",
        ),
        sa.ForeignKeyConstraint(["animal_id"], ["animals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["last_updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["recorder_id"], ["volunteers.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_care_logs_animal_id", "care_logs", ["animal_id"], unique=False)
    op.create_index(
        "ix_care_logs_created_at", "care_logs", ["created_at"], unique=False
    )
    op.create_index(
        "ix_care_logs_recorder_id", "care_logs", ["recorder_id"], unique=False
    )
    op.create_index("ix_care_logs_time_slot", "care_logs", ["time_slot"], unique=False)
    op.create_table(
        "medical_actions",
        sa.Column(
            "id", sa.Integer(), autoincrement=True, nullable=False, comment="主キー"
        ),
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=False,
            comment="診療名称（薬剤、ワクチン、検査等）",
        ),
        sa.Column("valid_from", sa.Date(), nullable=False, comment="適用開始日"),
        sa.Column("valid_to", sa.Date(), nullable=True, comment="適用終了日"),
        sa.Column(
            "cost_price",
            sa.Numeric(precision=10, scale=2),
            server_default="0.00",
            nullable=False,
            comment="原価（小数点2桁）",
        ),
        sa.Column(
            "selling_price",
            sa.Numeric(precision=10, scale=2),
            server_default="0.00",
            nullable=False,
            comment="請求価格（小数点2桁）",
        ),
        sa.Column(
            "procedure_fee",
            sa.Numeric(precision=10, scale=2),
            server_default="0.00",
            nullable=False,
            comment="投薬・処置料金（小数点2桁）",
        ),
        sa.Column(
            "currency",
            sa.String(length=3),
            server_default="JPY",
            nullable=False,
            comment="通貨単位（JPY/USD）",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="作成日時",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="更新日時",
        ),
        sa.Column(
            "last_updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="最終更新日時",
        ),
        sa.Column(
            "last_updated_by", sa.Integer(), nullable=True, comment="最終更新者ID"
        ),
        sa.ForeignKeyConstraint(["last_updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_medical_actions_name", "medical_actions", ["name"], unique=False
    )
    op.create_index(
        "ix_medical_actions_valid_from", "medical_actions", ["valid_from"], unique=False
    )
    op.create_index(
        "ix_medical_actions_valid_to", "medical_actions", ["valid_to"], unique=False
    )
    op.create_table(
        "sessions",
        sa.Column(
            "id", sa.Integer(), autoincrement=True, nullable=False, comment="主キー"
        ),
        sa.Column(
            "session_id",
            sa.String(length=255),
            nullable=False,
            comment="セッションID（ユニーク）",
        ),
        sa.Column("user_id", sa.Integer(), nullable=False, comment="ユーザーID"),
        sa.Column(
            "ip_address",
            sa.String(length=45),
            nullable=True,
            comment="IPアドレス（IPv6対応）",
        ),
        sa.Column(
            "user_agent",
            sa.String(length=255),
            nullable=True,
            comment="ユーザーエージェント",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="作成日時",
        ),
        sa.Column("expires_at", sa.DateTime(), nullable=False, comment="有効期限"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id"),
    )
    op.create_index("ix_sessions_expires_at", "sessions", ["expires_at"], unique=False)
    op.create_index("ix_sessions_session_id", "sessions", ["session_id"], unique=True)
    op.create_index("ix_sessions_user_id", "sessions", ["user_id"], unique=False)
    op.create_table(
        "status_history",
        sa.Column(
            "id", sa.Integer(), autoincrement=True, nullable=False, comment="主キー"
        ),
        sa.Column("animal_id", sa.Integer(), nullable=False, comment="猫ID"),
        sa.Column(
            "old_status",
            sa.String(length=20),
            nullable=True,
            comment="変更前ステータス",
        ),
        sa.Column(
            "new_status",
            sa.String(length=20),
            nullable=False,
            comment="変更後ステータス",
        ),
        sa.Column("reason", sa.Text(), nullable=True, comment="変更理由"),
        sa.Column("changed_by", sa.Integer(), nullable=True, comment="変更者ID"),
        sa.Column(
            "changed_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="変更日時",
        ),
        sa.ForeignKeyConstraint(["animal_id"], ["animals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["changed_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_status_history_animal_id", "status_history", ["animal_id"], unique=False
    )
    op.create_index(
        "ix_status_history_changed_at", "status_history", ["changed_at"], unique=False
    )
    op.create_table(
        "medical_records",
        sa.Column(
            "id", sa.Integer(), autoincrement=True, nullable=False, comment="主キー"
        ),
        sa.Column("animal_id", sa.Integer(), nullable=False, comment="猫ID"),
        sa.Column("vet_id", sa.Integer(), nullable=False, comment="獣医師ID"),
        sa.Column("date", sa.Date(), nullable=False, comment="診療日"),
        sa.Column("time_slot", sa.String(length=20), nullable=True, comment="時間帯"),
        sa.Column(
            "weight",
            sa.Numeric(precision=5, scale=2),
            nullable=False,
            comment="体重（kg、小数点2桁）",
        ),
        sa.Column(
            "temperature",
            sa.Numeric(precision=4, scale=1),
            nullable=True,
            comment="体温（℃、小数点1桁）",
        ),
        sa.Column("symptoms", sa.Text(), nullable=False, comment="症状"),
        sa.Column(
            "medical_action_id",
            sa.Integer(),
            nullable=True,
            comment="診療行為ID（マスターテーブル）",
        ),
        sa.Column("dosage", sa.Integer(), nullable=True, comment="投薬量・回数"),
        sa.Column("other", sa.Text(), nullable=True, comment="その他（ロット番号等）"),
        sa.Column("comment", sa.Text(), nullable=True, comment="コメント"),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="作成日時",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="更新日時",
        ),
        sa.Column(
            "last_updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
            comment="最終更新日時",
        ),
        sa.Column(
            "last_updated_by", sa.Integer(), nullable=True, comment="最終更新者ID"
        ),
        sa.ForeignKeyConstraint(["animal_id"], ["animals.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["last_updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["medical_action_id"], ["medical_actions.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["vet_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_medical_records_animal_id", "medical_records", ["animal_id"], unique=False
    )
    op.create_index(
        "ix_medical_records_date", "medical_records", ["date"], unique=False
    )
    op.create_index(
        "ix_medical_records_medical_action_id",
        "medical_records",
        ["medical_action_id"],
        unique=False,
    )
    op.create_index(
        "ix_medical_records_vet_id", "medical_records", ["vet_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_medical_records_vet_id", table_name="medical_records")
    op.drop_index("ix_medical_records_medical_action_id", table_name="medical_records")
    op.drop_index("ix_medical_records_date", table_name="medical_records")
    op.drop_index("ix_medical_records_animal_id", table_name="medical_records")
    op.drop_table("medical_records")
    op.drop_index("ix_status_history_changed_at", table_name="status_history")
    op.drop_index("ix_status_history_animal_id", table_name="status_history")
    op.drop_table("status_history")
    op.drop_index("ix_sessions_user_id", table_name="sessions")
    op.drop_index("ix_sessions_session_id", table_name="sessions")
    op.drop_index("ix_sessions_expires_at", table_name="sessions")
    op.drop_table("sessions")
    op.drop_index("ix_medical_actions_valid_to", table_name="medical_actions")
    op.drop_index("ix_medical_actions_valid_from", table_name="medical_actions")
    op.drop_index("ix_medical_actions_name", table_name="medical_actions")
    op.drop_table("medical_actions")
    op.drop_index("ix_care_logs_time_slot", table_name="care_logs")
    op.drop_index("ix_care_logs_recorder_id", table_name="care_logs")
    op.drop_index("ix_care_logs_created_at", table_name="care_logs")
    op.drop_index("ix_care_logs_animal_id", table_name="care_logs")
    op.drop_table("care_logs")
    op.drop_index("ix_audit_logs_user_id", table_name="audit_logs")
    op.drop_index("ix_audit_logs_target_type", table_name="audit_logs")
    op.drop_index("ix_audit_logs_created_at", table_name="audit_logs")
    op.drop_index("ix_audit_logs_action", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index("ix_animal_images_taken_at", table_name="animal_images")
    op.drop_index("ix_animal_images_animal_id", table_name="animal_images")
    op.drop_table("animal_images")
    op.drop_index("ix_adoption_records_applicant_id", table_name="adoption_records")
    op.drop_index("ix_adoption_records_animal_id", table_name="adoption_records")
    op.drop_index("ix_adoption_records_adoption_date", table_name="adoption_records")
    op.drop_table("adoption_records")
    op.drop_index("ix_volunteers_status", table_name="volunteers")
    op.drop_index("ix_volunteers_name", table_name="volunteers")
    op.drop_table("volunteers")
    op.drop_index("ix_users_role", table_name="users")
    op.drop_index("ix_users_email", table_name="users")
    op.drop_table("users")
    op.drop_index("ix_settings_key", table_name="settings")
    op.drop_table("settings")
    op.drop_index("ix_applicants_name", table_name="applicants")
    op.drop_index("ix_applicants_contact", table_name="applicants")
    op.drop_table("applicants")
    op.drop_index("ix_animals_status", table_name="animals")
    op.drop_index("ix_animals_protected_at", table_name="animals")
    op.drop_index("ix_animals_name", table_name="animals")
    op.drop_table("animals")
    # ### end Alembic commands ###
