#!/usr/bin/env python3
"""
本番サンプルの猫データをローカルDBへ投入するスクリプト。

- 現在の animals テーブルを全削除してから、提示された27件をそのまま挿入します。
- ステータス値は本番のまま（"In Care" / "Adoptable" / "Treatment" 等）を保持し、
  再現データとして使えるようにしています。
- ログイン不要で `python scripts/load_sample_animals_from_prod.py` で実行できます。

注意:
- 既存の動物データはすべて削除されます。必要なら事前にバックアップしてください。
"""

from __future__ import annotations

import sys
from datetime import date, datetime
from pathlib import Path

from sqlalchemy import delete

# プロジェクトルートを import パスに追加
ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from app.database import SessionLocal
from app.models.animal import Animal

DATA = [
    {
        "id": 1,
        "name": "Luna",
        "photo": "/media/animals/1/gallery/e908ec7b350b4c258769dd75eb637b7b.png",
        "tail_length": "Long",
        "collar": None,
        "gender": "female",
        "ear_cut": 0,
        "features": "Friendly and calm. Loves being petted. Very gentle with people.",
        "status": "ADOPTED",
        "protected_at": "2025-06-15",
        "created_at": "2025-06-15 23:00:00",
        "updated_at": "2025-12-18 01:08:02.106765",
        "age_months": None,
        "age_is_estimated": 0,
        "rescue_source": None,
        "breed": None,
        "microchip_number": None,
        "location_type": "FACILITY",
        "current_location_note": None,
        "coat_color": "Black",
        "coat_color_note": None,
    },
    {
        "id": 2,
        "name": "Oliver",
        "photo": "/media/animals/2/gallery/80e8abad10f4411d983bd51be2fc2f83.png",
        "tail_length": "Long",
        "collar": "Blue collar with bell",
        "gender": "male",
        "ear_cut": 0,
        "features": "Playful and curious. Gets along well with other cats. Loves toys.",
        "status": "In Care",
        "protected_at": "2025-08-20",
        "created_at": "2025-08-20 20:00:00",
        "updated_at": "2025-12-06 23:10:30.728311",
        "age_months": None,
        "age_is_estimated": 0,
        "rescue_source": None,
        "breed": None,
        "microchip_number": None,
        "location_type": "FACILITY",
        "current_location_note": None,
        "coat_color": "Ginger (Orange tabby)",
        "coat_color_note": None,
    },
    {
        "id": 3,
        "name": "Misty",
        "photo": "/media/animals/3/gallery/53ec6a8a29fb475cb81d831eae29e873.png",
        "tail_length": "長い",
        "collar": "あり",
        "gender": "female",
        "ear_cut": 0,
        "features": "Quiet and independent. Prefers to be the only pet. Enjoys sunny spots.",
        "status": "ADOPTED",
        "protected_at": "2025-04-10",
        "created_at": "2025-04-11 00:00:00",
        "updated_at": "2025-12-18 01:07:20.916076",
        "age_months": None,
        "age_is_estimated": 0,
        "rescue_source": None,
        "breed": None,
        "microchip_number": None,
        "location_type": "FACILITY",
        "current_location_note": None,
        "coat_color": "White",
        "coat_color_note": None,
    },
    {
        "id": 4,
        "name": "Shadow",
        "photo": "/media/animals/4/gallery/83d9622d7be24b9b92e18b6bcdd0f1c9.png",
        "tail_length": "長い",
        "collar": "あり",
        "gender": "male",
        "ear_cut": 1,
        "features": "Shy at first but very affectionate once comfortable. Ear-tipped (TNR). Currently receiving treatment for eye condition.",
        "status": "Treatment",
        "protected_at": "2025-09-05",
        "created_at": "2025-09-05 18:00:00",
        "updated_at": "2025-12-06 23:10:16.012238",
        "age_months": None,
        "age_is_estimated": 0,
        "rescue_source": None,
        "breed": None,
        "microchip_number": None,
        "location_type": "FACILITY",
        "current_location_note": None,
        "coat_color": "Grey",
        "coat_color_note": None,
    },
    {
        "id": 5,
        "name": "Bella",
        "photo": "/media/animals/5/gallery/0f7a173c0cbc46e7a4ac1894d88d68f4.png",
        "tail_length": "Short",
        "collar": "Pink collar",
        "gender": "female",
        "ear_cut": 0,
        "features": "Very energetic and playful. Good with children. Loves climbing and exploring.",
        "status": "Adoptable",
        "protected_at": "2025-09-20",
        "created_at": "2025-09-21 01:00:00",
        "updated_at": "2025-12-06 22:23:24.850484",
        "age_months": None,
        "age_is_estimated": 0,
        "rescue_source": None,
        "breed": None,
        "microchip_number": None,
        "location_type": "FACILITY",
        "current_location_note": None,
        "coat_color": "Calico",
        "coat_color_note": None,
    },
    {
        "id": 6,
        "name": "Patches",
        "photo": "/media/animals/6/gallery/5b2b3134947a445c8521104a86e5074b.png",
        "tail_length": "長い",
        "collar": "あり",
        "gender": "female",
        "ear_cut": 0,
        "features": "Young female calico with distinctive tri-color markings of white, orange, and black. Alert and curious personality. Appears healthy and well-socialized with a gentle demeanor.",
        "status": "ADOPTED",
        "protected_at": "2025-12-02",
        "created_at": "2025-12-02 02:08:48",
        "updated_at": "2025-12-21 10:52:33.677156",
        "age_months": None,
        "age_is_estimated": 0,
        "rescue_source": None,
        "breed": None,
        "microchip_number": None,
        "location_type": "FACILITY",
        "current_location_note": None,
        "coat_color": "Calico",
        "coat_color_note": None,
    },
    {
        "id": 7,
        "name": "トモエ",
        "photo": "/media/animals/7/gallery/befc24998add4a3fbf66dfa27e243f9f.jpg",
        "tail_length": "短い",
        "collar": None,
        "gender": "female",
        "ear_cut": 0,
        "features": "新松戸七丁目\n年齢10歳",
        "status": "TRIAL",
        "protected_at": "2025-07-11",
        "created_at": "2025-12-14 21:45:44.701901",
        "updated_at": "2026-01-09 08:02:57.091498",
        "age_months": None,
        "age_is_estimated": 0,
        "rescue_source": None,
        "breed": None,
        "microchip_number": None,
        "location_type": "FACILITY",
        "current_location_note": None,
        "coat_color": "黒",
        "coat_color_note": None,
    },
    {
        "id": 8,
        "name": "がく",
        "photo": "/media/animals/8/gallery/a591d1f1607a48788e8a8e7cea332a52.jpg",
        "tail_length": "短い",
        "collar": None,
        "gender": "male",
        "ear_cut": 0,
        "features": "新松戸七丁目\u3000２歳",
        "status": "ADOPTED",
        "protected_at": "2025-07-11",
        "created_at": "2025-12-14 21:57:26.470593",
        "updated_at": "2026-01-09 08:03:15.334570",
        "age_months": None,
        "age_is_estimated": 0,
        "rescue_source": None,
        "breed": None,
        "microchip_number": None,
        "location_type": "FACILITY",
        "current_location_note": None,
        "coat_color": "黒",
        "coat_color_note": None,
    },
    {
        "id": 9,
        "name": "ヨンコ",
        "photo": "/media/animals/9/gallery/dc26af68cd9443f3812d4425ec77ee3e.jpg",
        "tail_length": "長い",
        "collar": None,
        "gender": "female",
        "ear_cut": 0,
        "features": "９歳、MIX\u3000江戸川さん経由",
        "status": "TRIAL",
        "protected_at": "2025-05-14",
        "created_at": "2025-12-14 22:59:05.725552",
        "updated_at": "2026-01-09 08:03:58.658328",
        "age_months": None,
        "age_is_estimated": 0,
        "rescue_source": None,
        "breed": None,
        "microchip_number": None,
        "location_type": "FACILITY",
        "current_location_note": None,
        "coat_color": "茶色と黒のぶち",
        "coat_color_note": None,
    },
    {
        "id": 10,
        "name": "ぽじ",
        "photo": "/media/animals/10/gallery/0310a60d8f734ae6a1b309501b9aeefe.jpg",
        "tail_length": "長い",
        "collar": None,
        "gender": "male",
        "ear_cut": 0,
        "features": "動物愛護センター東葛飾支所\u3000MIX",
        "status": "TRIAL",
        "protected_at": "2025-06-11",
        "created_at": "2025-12-14 23:15:47.781007",
        "updated_at": "2026-01-09 08:06:16.247279",
        "age_months": None,
        "age_is_estimated": 0,
        "rescue_source": None,
        "breed": None,
        "microchip_number": None,
        "location_type": "FACILITY",
        "current_location_note": None,
        "coat_color": "黒白のぶち",
        "coat_color_note": None,
    },
    {
        "id": 11,
        "name": "クロル",
        "photo": "/media/animals/11/gallery/79b38df05c104a58916d147d4b3f8a44.jpg",
        "tail_length": "長い",
        "collar": None,
        "gender": "female",
        "ear_cut": 0,
        "features": "長門さん、\u3000黒猫\u3000、mix",
        "status": "QUARANTINE",
        "protected_at": "2025-06-20",
        "created_at": "2025-12-14 23:32:59.314388",
        "updated_at": "2025-12-14 23:33:00.415838",
        "age_months": None,
        "age_is_estimated": 0,
        "rescue_source": None,
        "breed": None,
        "microchip_number": None,
        "location_type": "FACILITY",
        "current_location_note": None,
        "coat_color": "黒",
        "coat_color_note": None,
    },
    {
        "id": 12,
        "name": "ポップ",
        "photo": "/media/animals/12/gallery/2fe19b0f70bf45429cd05dfe68e06a23.jpg",
        "tail_length": "短い",
        "collar": None,
        "gender": "female",
        "ear_cut": 0,
        "features": "MIX 中港さん 6か月",
        "status": "QUARANTINE",
        "protected_at": "2025-06-10",
        "created_at": "2025-12-15 07:19:06.753572",
        "updated_at": "2025-12-15 07:19:08.503273",
        "age_months": None,
        "age_is_estimated": 0,
        "rescue_source": None,
        "breed": None,
        "microchip_number": None,
        "location_type": "FACILITY",
        "current_location_note": None,
        "coat_color": "＊＊",
        "coat_color_note": None,
    },
    {
        "id": 13,
        "name": "アミ",
        "photo": "/media/animals/13/gallery/3131b23d35604c7395c6410f82be1618.jpg",
        "tail_length": "短い",
        "collar": None,
        "gender": "female",
        "ear_cut": 0,
        "features": "MIX、白猫、ツノのような黒毛、中港さん、６か月",
        "status": "ADOPTED",
        "protected_at": "2025-12-14",
        "created_at": "2025-12-15 07:32:09.412254",
        "updated_at": "2026-01-09 08:05:48.702809",
        "age_months": None,
        "age_is_estimated": 0,
        "rescue_source": None,
        "breed": None,
        "microchip_number": None,
        "location_type": "FACILITY",
        "current_location_note": None,
        "coat_color": "白猫、ツノのような黒毛",
        "coat_color_note": None,
    },
    {
        "id": 14,
        "name": "むい",
        "photo": "/media/animals/14/gallery/805319f2b4914ce4bf2ad88612e73904.jpg",
        "tail_length": "長い",
        "collar": None,
        "gender": "male",
        "ear_cut": 0,
        "features": "新松戸6丁目、5カ月",
        "status": "TRIAL",
        "protected_at": "2025-07-13",
        "created_at": "2025-12-16 19:00:26.607650",
        "updated_at": "2026-01-09 08:05:22.949524",
        "age_months": None,
        "age_is_estimated": 0,
        "rescue_source": None,
        "breed": None,
        "microchip_number": None,
        "location_type": "FACILITY",
        "current_location_note": None,
        "coat_color": "茶白、活発",
        "coat_color_note": None,
    },
    {
        "id": 15,
        "name": "キラ",
        "photo": "/media/animals/15/gallery/d2714f1b461b4415be230122c56bf950.jpg",
        "tail_length": "長い",
        "collar": None,
        "gender": "female",
        "ear_cut": 0,
        "features": "MIX\u3000新松戸6丁目\u30005か月",
        "status": "ADOPTED",
        "protected_at": "2025-12-16",
        "created_at": "2025-12-16 19:05:02.127595",
        "updated_at": "2026-01-09 08:04:52.069464",
        "age_months": None,
        "age_is_estimated": 0,
        "rescue_source": None,
        "breed": None,
        "microchip_number": None,
        "location_type": "FACILITY",
        "current_location_note": None,
        "coat_color": "黒白がら",
        "coat_color_note": None,
    },
    {
        "id": 16,
        "name": "ふぉーく",
        "photo": "/media/animals/16/gallery/fe0586d6cfaf43f8bb0929ea29716dad.jpg",
        "tail_length": "長い",
        "collar": None,
        "gender": "male",
        "ear_cut": 0,
        "features": "MIX\u3000新松戸6丁目\u30001か月",
        "status": "ADOPTED",
        "protected_at": "2025-07-13",
        "created_at": "2025-12-16 19:17:40.257705",
        "updated_at": "2026-01-09 08:02:25.585500",
        "age_months": None,
        "age_is_estimated": 0,
        "rescue_source": None,
        "breed": None,
        "microchip_number": None,
        "location_type": "FACILITY",
        "current_location_note": None,
        "coat_color": "キジトラ、湯浅さんお預かり",
        "coat_color_note": None,
    },
    {
        "id": 17,
        "name": "じゃず",
        "photo": "/media/animals/17/gallery/af42ec78710f4b81bcfd4eec72d28a33.jpg",
        "tail_length": "長い",
        "collar": "あり",
        "gender": "male",
        "ear_cut": 0,
        "features": "MIX\u30003か月\u3000新松戸6丁目",
        "status": "ADOPTED",
        "protected_at": "2025-10-03",
        "created_at": "2025-12-16 19:20:55.579590",
        "updated_at": "2026-01-09 08:02:01.143744",
        "age_months": None,
        "age_is_estimated": 0,
        "rescue_source": None,
        "breed": None,
        "microchip_number": None,
        "location_type": "FACILITY",
        "current_location_note": None,
        "coat_color": "白、グレイ",
        "coat_color_note": None,
    },
    {
        "id": 18,
        "name": "マリ",
        "photo": "/media/animals/18/gallery/071e8168caaa4503967023278b8e6296.jpg",
        "tail_length": "長い",
        "collar": None,
        "gender": "female",
        "ear_cut": 0,
        "features": "MIX\u3000新松戸6丁目、プリモ→ろくねこ\u30001か月\n",
        "status": "QUARANTINE",
        "protected_at": "2025-07-31",
        "created_at": "2025-12-16 19:44:29.591343",
        "updated_at": "2025-12-16 19:44:37.029352",
        "age_months": None,
        "age_is_estimated": 0,
        "rescue_source": None,
        "breed": None,
        "microchip_number": None,
        "location_type": "FACILITY",
        "current_location_note": None,
        "coat_color": "黒",
        "coat_color_note": None,
    },
    {
        "id": 19,
        "name": "ラン",
        "photo": "/media/animals/19/gallery/aa0e5888fd9847a5830024c3e3900124.jpg",
        "tail_length": "短い",
        "collar": None,
        "gender": "male",
        "ear_cut": 0,
        "features": "mix, 新松戸6丁目、プリモ→ろくねこ",
        "status": "ADOPTED",
        "protected_at": "2025-07-31",
        "created_at": "2025-12-20 04:43:50.175151",
        "updated_at": "2026-01-09 08:01:07.905436",
        "age_months": None,
        "age_is_estimated": 0,
        "rescue_source": None,
        "breed": None,
        "microchip_number": None,
        "location_type": "FACILITY",
        "current_location_note": None,
        "coat_color": "キジ",
        "coat_color_note": None,
    },
    {
        "id": 20,
        "name": "わへい",
        "photo": "/media/animals/20/gallery/8a729b2649694643b31438067a1ce88d.jpg",
        "tail_length": "短い",
        "collar": None,
        "gender": "male",
        "ear_cut": 0,
        "features": "Miｘ新松戸6丁目",
        "status": "ADOPTED",
        "protected_at": "2025-12-19",
        "created_at": "2025-12-20 04:47:06.852190",
        "updated_at": "2026-01-09 08:00:50.783580",
        "age_months": None,
        "age_is_estimated": 0,
        "rescue_source": None,
        "breed": None,
        "microchip_number": None,
        "location_type": "FACILITY",
        "current_location_note": None,
        "coat_color": "茶トラ白",
        "coat_color_note": None,
    },
    {
        "id": 21,
        "name": "チアキ",
        "photo": "/media/animals/21/gallery/c6a2042e10674f1287430008f886121b.jpg",
        "tail_length": "短い",
        "collar": "あり",
        "gender": "female",
        "ear_cut": 0,
        "features": "Mix\u3000新松戸6丁目",
        "status": "ADOPTED",
        "protected_at": "2025-08-27",
        "created_at": "2025-12-20 04:49:43.394151",
        "updated_at": "2026-01-09 08:00:25.123889",
        "age_months": None,
        "age_is_estimated": 0,
        "rescue_source": None,
        "breed": None,
        "microchip_number": None,
        "location_type": "FACILITY",
        "current_location_note": None,
        "coat_color": "サビ（茶黒）",
        "coat_color_note": None,
    },
    {
        "id": 22,
        "name": "ほくと",
        "photo": "/media/animals/22/gallery/3d5394ae2513458c98b46a4418a3fbf7.jpg",
        "tail_length": "短い",
        "collar": "あり",
        "gender": "male",
        "ear_cut": 0,
        "features": "雑種\u3000ウイング田中\u3000\u30002ヶ月",
        "status": "ADOPTED",
        "protected_at": "2025-11-04",
        "created_at": "2025-12-20 04:52:40.700906",
        "updated_at": "2026-01-09 07:59:41.461107",
        "age_months": None,
        "age_is_estimated": 0,
        "rescue_source": None,
        "breed": None,
        "microchip_number": None,
        "location_type": "FACILITY",
        "current_location_note": None,
        "coat_color": "ほぼ白",
        "coat_color_note": None,
    },
    {
        "id": 23,
        "name": "けん",
        "photo": "/media/animals/23/gallery/4adde7bf06284196b3f0b892a769fd93.jpg",
        "tail_length": "長い",
        "collar": None,
        "gender": "male",
        "ear_cut": 0,
        "features": "ウイング田中",
        "status": "ADOPTED",
        "protected_at": "2025-11-04",
        "created_at": "2025-12-20 04:56:31.311727",
        "updated_at": "2026-01-09 07:59:22.215369",
        "age_months": None,
        "age_is_estimated": 0,
        "rescue_source": None,
        "breed": None,
        "microchip_number": None,
        "location_type": "FACILITY",
        "current_location_note": None,
        "coat_color": "白黒",
        "coat_color_note": None,
    },
    {
        "id": 24,
        "name": "まさお",
        "photo": "/media/animals/24/gallery/ff2fee1e688d42e4a7bfca95c5c4e72a.jpg",
        "tail_length": "長い",
        "collar": None,
        "gender": "male",
        "ear_cut": 0,
        "features": "Mix\u3000新松戸6丁目",
        "status": "IN_CARE",
        "protected_at": "2025-12-19",
        "created_at": "2025-12-20 04:59:47.527779",
        "updated_at": "2026-01-09 07:59:01.830119",
        "age_months": None,
        "age_is_estimated": 0,
        "rescue_source": None,
        "breed": None,
        "microchip_number": None,
        "location_type": "FACILITY",
        "current_location_note": None,
        "coat_color": "パステルキジ白",
        "coat_color_note": None,
    },
    {
        "id": 25,
        "name": "ふみ",
        "photo": "/media/animals/25/gallery/59d35921d1ed471f94fbe114bd67077e.jpg",
        "tail_length": "短い",
        "collar": None,
        "gender": "male",
        "ear_cut": 0,
        "features": "雑種",
        "status": "QUARANTINE",
        "protected_at": "2025-11-19",
        "created_at": "2025-12-20 05:04:00.620289",
        "updated_at": "2025-12-20 05:04:02.239784",
        "age_months": None,
        "age_is_estimated": 0,
        "rescue_source": None,
        "breed": None,
        "microchip_number": None,
        "location_type": "FACILITY",
        "current_location_note": None,
        "coat_color": "キジ白",
        "coat_color_note": None,
    },
    {
        "id": 26,
        "name": "ルル",
        "photo": "/media/animals/26/gallery/a77afe77e8384730b31b3c7b1db63ca9.jpg",
        "tail_length": "短い",
        "collar": None,
        "gender": "female",
        "ear_cut": 0,
        "features": "新松戸6丁目",
        "status": "QUARANTINE",
        "protected_at": "2025-11-19",
        "created_at": "2025-12-20 05:07:19.863763",
        "updated_at": "2025-12-20 05:07:21.108138",
        "age_months": None,
        "age_is_estimated": 0,
        "rescue_source": None,
        "breed": None,
        "microchip_number": None,
        "location_type": "FACILITY",
        "current_location_note": None,
        "coat_color": "キジ白",
        "coat_color_note": None,
    },
    {
        "id": 27,
        "name": "望",
        "photo": "/media/animals/27/gallery/a49da6dd850b47d4b58663f0b1a250f6.jpg",
        "tail_length": "短い",
        "collar": None,
        "gender": "female",
        "ear_cut": 0,
        "features": "雑種\u30004ヶ月",
        "status": "QUARANTINE",
        "protected_at": "2025-12-10",
        "created_at": "2025-12-20 05:10:15.736306",
        "updated_at": "2025-12-20 05:10:17.522345",
        "age_months": None,
        "age_is_estimated": 0,
        "rescue_source": None,
        "breed": None,
        "microchip_number": None,
        "location_type": "FACILITY",
        "current_location_note": None,
        "coat_color": "キジトラ",
        "coat_color_note": None,
    },
]


def parse_date(value: str) -> date:
    return datetime.strptime(value, "%Y-%m-%d").date()


def parse_datetime(value: str) -> datetime:
    # 秒以下の桁が短い場合もゼロパディングを許容するため、fromisoformat を利用
    return datetime.fromisoformat(value)


def main() -> None:
    db = SessionLocal()
    try:
        # 既存データを削除
        db.execute(delete(Animal))
        db.commit()

        for row in DATA:
            animal = Animal(
                id=row["id"],
                name=row["name"],
                photo=row["photo"],
                tail_length=row["tail_length"],
                collar=row["collar"],
                gender=row["gender"],
                ear_cut=bool(row["ear_cut"]),
                features=row["features"],
                status=row["status"],  # レガシー値をそのまま入れて再現
                protected_at=parse_date(row["protected_at"]),
                created_at=parse_datetime(row["created_at"]),
                updated_at=parse_datetime(row["updated_at"]),
                age_months=row["age_months"],
                age_is_estimated=bool(row["age_is_estimated"]),
                rescue_source=row["rescue_source"],
                breed=row["breed"],
                microchip_number=row["microchip_number"],
                location_type=row["location_type"],
                current_location_note=row["current_location_note"],
                coat_color=row["coat_color"],
                coat_color_note=row["coat_color_note"],
            )
            db.add(animal)

        db.commit()
        print(f"Inserted {len(DATA)} animals (existing data was cleared).")
    finally:
        db.close()


if __name__ == "__main__":
    main()
